---
- hosts: all
  sudo: yes
  tasks:
    - name: supervisorctl stop
      supervisorctl: name=cleverup-crm-frontend state=stopped
- hosts: all
  sudo: no
  tasks:
    - name: checkout project
      git: repo=git@bitbucket.org:icu0755/cleverup-crm-django.git dest=/opt/cleverup update=yes version=master force=yes
    - name: bower install
      bower: /opt/cleverup
    - name: collect static
      django_manage:
        command: collectstatic
        app_path: /opt/cleverup/crm
        settings: frontend.settings.prod
        virtualenv: /opt/cleverup/env
    - name: migrate
      django_manage:
        command: migrate
        app_path: /opt/cleverup/crm
        settings: frontend.settings.prod
        virtualenv: /opt/cleverup/env
- hosts: all
  sudo: yes
  tasks:
    - name: supervisorctl stop
      supervisorctl: name=cleverup-crm-frontend state=stopped
    - name: supervisorctl reread
      shell: supervisorctl reread
    - name: supervisorctl update
      shell: supervisorctl update
    - name: supervisorctl start
      supervisorctl: name=cleverup-crm-frontend state=started
